dist: xenial
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - cppcheck
before_install:
    - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update -q
    - sudo apt-get install -y gcc-arm-embedded
script:
  - export CC=gcc-7
  - make travis
