site_name: Solo Technical Documentation
site_author: SoloKeys
site_description: 'Documentation for the SoloKeys solo software'
site_url: 'https://docs.solokeys.io/solo/'
repo_url: 'https://github.com/solokeys/solo'
repo_name: 'solokeys/solo'
copyright: 'Copyright &copy; 2018 - 2019 SoloKeys'

nav:
    - Home: index.md
    - FIDO2 Implementation: fido2-impl.md
    - Build instructions: building.md
    - Signed update process: signed-updates.md
    - Code documentation: code-overview.md
    - Contributing Code: contributing.md
    - Contributing Docs: documenting.md
    - udev Rules: udev.md
    - About: repo-readme.md

theme:
  name: material
  logo: 'solo/images/logo.svg'
  favicon: 'solo/images/favicon.ico'
